version: '3.8'

services:
  # gcPanel Construction Management Application
  gcpanel:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: gcpanel-construction-management
    ports:
      - "5000:5000"
    environment:
      # Application Configuration
      - APP_NAME=gcPanel Construction Management
      - APP_VERSION=2.0.0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      
      # Security Keys
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=5000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_SERVER_MAX_MESSAGE_SIZE=200
      - STREAMLIT_THEME_BASE=light
      
      # External API Keys (Optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER:-}
      
    volumes:
      - gcpanel_data:/app/data
      - gcpanel_logs:/app/logs
      - gcpanel_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - gcpanel_network

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: gcpanel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - gcpanel_network
    profiles:
      - caching

volumes:
  gcpanel_data:
    driver: local
  gcpanel_logs:
    driver: local
  gcpanel_uploads:
    driver: local
  redis_data:
    driver: local

networks:
  gcpanel_network:
    driver: bridge