apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcpanel-data-pvc
  namespace: gcpanel
  labels:
    app: gcpanel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcpanel-logs-pvc
  namespace: gcpanel
  labels:
    app: gcpanel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcpanel-uploads-pvc
  namespace: gcpanel
  labels:
    app: gcpanel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi