apiVersion: v1
kind: Namespace
metadata:
  name: highland-tower
  labels:
    name: highland-tower
    project: gcpanel
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: highland-tower-quota
  namespace: highland-tower
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"