[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#1e40af"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
base = "dark"

[browser]
gatherUsageStats = false
